### ISSUE TITLE
Change signature of map to (List a -> List b) -> PaginatedList a -> PaginatedList b

### ISSUE THREAD

**Issue by tracker-common** [jschomay/elm-paginate#5]
This would be more compliant with how List.map works. For example, take a PaginatedList of Person and map it to a PaginatedList of String (name)

Should also do this for Paginate.Custom.map

**Comment by jschomay** [comment]
I realize this is a very late response (I probably responded in person when this was asked), but for others who find this issue, I'll respond now and close this.

This is a common question, since most people are used to `map` as a function that applies to `List`, but `map` is actually a generic concept that simply "lifts" the provided function "over" the outer structure to operate on the value "wrapped" within.

In other words, use `PaginatedList.map` to get "through" the `PaginatedList`  type, so that your function can work on the `List` inside it.  (The same concept applies to `Paginate.Custom`).  

Consider this: Let's say I want to do some filtering or sorting instead of mapping.  If I changed `map` to work as suggested, I would need to add a `filter` and `sort` as well.  Ultimately, I'd be recreating the `List` api, which is not the point of `PaginatedList`.  With `Paginated.Custom` this becomes even more apparent - since I don't know what the data structure is inside, I actually cannot provide the api for manipulating it.

Instead, the designed usage is to use `PaginatedList.map` with a function that applies to a `List`.  For example:

    names = PaginatedList.map (List.map .name) paginatedPeople

For those of you familiar with the [Law of Functors](https://en.wikibooks.org/wiki/Haskell/The_Functor_class#The_functor_laws), the code below is equivalent to the code above, and perhaps is more expressive of the intent to "jump over both the Paginated type and the List type, to apply this function to the value(s) inside):

    names = (PaginatedList.map >> List.map) .name paginatedPeople

See the README for similar examples on how the same technique applies to `filter`, `sort`, `cons` etc.

**Comment by kalawr** [comment]
Hi @jschomay! Sorry I have to bring up this conversation again after all this time. I believe the original poster meant changing type signature from:
`map : (List a -> List a) -> PaginatedList a -> PaginatedList a` to
`map : (List a -> List b) -> PaginatedList a -> PaginatedList b`. 

The example you mentioned above (`names = PaginatedList.map (List.map .name) paginatedPeople`) would not compile with the current definition of `map`, since it does not allow to change the type of value within a list. Does it make sense?

This suggestion, if applied, would keep the current use-cases possible, but would also allow a class of use-cases that are currently not supported. The API is great and expressive otherwise, I agree that it's a rational alternative to having to recreate the `List` API. Thanks for the great work!

**Comment by jschomay** [comment]
Hi @kalawr.  I'm glad this package is still useful and still being used!  Thanks for reaching out.  I do see now that my example causes a compile error, and should be changed.  I'd be happy to accept a pull request.

In the meantime, I think everything works fine if you treat `Paginate.map` as a tool for sorting and filtering the wrapped list, but not changing the items in the list, then when you call `Paginate.page` you can map the items inside as you need:

```
names = myPaginatedPeopleList |> Paginate.map filterOnlyAdmins |> Paginate.page |> List.map .name
```

**Comment by kalawr** [comment]
Hey Jeff! Thanks for the reply! This is nice workaround to the limitation. I tried changing the type signatures of `Paginate.map` and `Paginate.Custom.map`, but this seems to require bumping the package to a new major version (4.0.0). Not sure if something as minor as this is worth the hassle 😄

**Comment by jschomay** [comment]
If you have a PR I think I can handle the bumping (it's been a long time
since I've done this, but I think it will still work).
