### ISSUE TITLE
Allow specifying max pager items

### ISSUE THREAD

**Issue by jesse-c** [jschomay/elm-paginate#6]
Have you considered adding the ability to specify the max number of items that the pager would create? For example like in this table where there is the ellipsis in the middle: ![](https://dab1nmslvvntp.cloudfront.net/wp-content/uploads/2016/10/1477811108dynatable.jpg)

**Comment by jschomay** [comment]
Hello Jesse, thank you for your suggestion.

At first, I was going to say that `pager` returns a `List` and from that point on it is up to the consuming code to slice or partition that list as it sees fit, and is outside the concerns of the `PaginatedList`.

However, I have had to do exactly what you are requesting, and it turns out to be more complex than you might think, so perhaps adding this as a utility would be helpful.

Let me sketch out the complexity involved, and how I would solve it, to get your feedback before I write any code.

---

Definitions:
`max` - maximum number of indexed buttons that link to specific pages, including the buffers (things like prev/next/first/last and "..." are not included)

`buffer` - number of indexed buttons that always show the beginning and end of the pager (these will never get elided) (`buffer * 2` should be less than `max`).

This makes a design decision that the active page should always have at least 1 page to its left and right.  For example, this is how paginating 20 pages with a max of 7 and a buffer of 2 would look:

    [1] 2 3 4 5 ... 19 20
    1 [2] 3 4 5 ... 19 20
    1 2 [3] 4 5 ... 19 20
    1 2 3 [4] 5 ... 19 20
    1 2 ... 4 [5] 6 ... 19 20
    1 2 ... 5 [6] 7... 19 20
    1 2 ... 6 [7] 8 ... 19 20
    etc...
    1 2 ... 15 [16] 17 ... 19 20
    1 2 ... 16 [17] 18 19 20
    1 2 ... 16 17 [18] 19 20
    1 2 ... 16 17 18 [19] 20
    1 2 ... 16 17 18 19 [20]


Also note that the buffer could be 0 to get something more like google's approach:

![image](https://user-images.githubusercontent.com/1825491/42393764-6a698606-810c-11e8-8473-7c9a14330878.png)

---

Given `max = 7`, `buffer = 2` for each case.

### Case 1: Equal to or fewer pages than `max`

All pages should show:

Given: 4 pages, page 3 is active.

    1 2 [3] 4

Given: 7 pages, page 3 is active.

    1 2 [3] 4 5 6 7

### Case 2: More pages than max, active page at "beginning"

Where "beginning" means `activePage <= max - buffer - 1`

Show first `max - buffer` pages, then "...", then last `buffer` pages

Given 20 pages, page 1 is active

    [1] 2 3 4 5 ... 19 20

Given 20 pages, page 4 (7 - 2 -1) is active

    1 2 3 [4] 5 ... 19 20

### Case 3: More pages than max, active page at "end"

Where "end" means `activePage >= totalPages - max + buffer + 1 + 1`

Show first `buffer` pages, then "...", then last `max - buffer` pages

Given 20 pages, page 20 is active

    1 2 ... 16 17 18 19 [20]

Given 20 pages, page 17 (20 - 7 + 2 + 1 + 1)  is active

    1 2 ... 16 [17] 18 19 20

### Case 4: More pages than max, active page at "middle"

Where "middle" means not beginning or end

Show first `buffer` pages, then "...", then `max - buffer - buffer` pages centered around `activePage`, then "...", then last `max - buffer` pages

Given 20 pages, page 5 is active

    1 2 ... 4 [5] 6 ... 19 20

Given 20 pages, page 16  is active

    1 2 ... 15 [16] 17 ... 19 20

Given 20 pages, page 10  is active

    1 2 ... 9 [10] 11 ... 19 20

---

So... what do you think?

**Comment by jesse-c** [comment]
That all sounds good! You're right about the complexity with the number of cases that needed to be considered. I started writing something myself at first and noticed it fairly quickly. From memory you've covered the cases.

With this approach, would it be possible to have something the current page without neighbouring indices? E.g. « ‹ 1, 2, .., 7, .., 9, 10 › »? It'd be setting a buffer of 2, and a max of 5?

**Comment by jschomay** [comment]
Cool.  I think buffer 2, max 5 would give that result with the logic I described above.  (Though design-wise, I'm not sure if that is useful).

If you are happy with this approach, would you be interested in making a PR that adds an `elidedPager` function with the basic logic outlined above?

**Comment by jesse-c** [comment]
I'll happily take a stab at it! Just fyi that I might be a bit slow moving though with my current work schedule.

**Comment by jschomay** [comment]
Cool :)
No time pressure.  Let me know if you have any questions about any of it.  I expect it would look a lot like `pager` with the extra partitioning logic between the range and the map.

What do you think the signature should look like?  Especially the return type?  I was thinking maybe something like this:

    elidedPager : {max: Int, buffers: int} -> (Int -> Bool -> b) -> Paginated a -> List (List b)

Then users could do something like `elidedPager myPagerConfig myPagerItemsView myPaginatedList |> List.intersperse [myPagerSeparatorView] |> List.concat`.  (Or they could use `List.Extra.intercalate` to do the same thing.)

I thought returning a `List(List b)` to be intercalated with their separator view would be cleaner to deal with than something like `{beginning : Maybe (List b), middle: List (b), end: Maybe (List b)`.  Obviously, in the implementation, the returned `List (List b)` would have 1, 2, or 3 items in it, no more no less, so the semantics are a little off, but the usage is clean.

Alternatively, the signature could be:

        elidedPager : {max: Int, buffesr: int, pageNumberView: (Int -> Bool -> b), separatorView: b} -> Paginated a -> List b

And we would just do the intercalation for them.  This is less flexible, but more directly usable.

Also, side note, I use the parametric `b` instead of `Html msg` just to be more flexible.  Maybe they are rendering a string or svg or something.

What are your thoughts?

**Comment by jschomay** [comment]
Closed by #8
